export const metadata = {
  title: "Alpha",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <div className="absolute top-0 right-0 bg-black/30 backdrop-blur z-20 h-screen w-full flex items-center justify-center ">
      {children}
    </div>
  );
}
