export const metadata = {
  title: "Alpha",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <div className="bg-black/30  h-full w-full flex items-center justify-center ">
      {children}
    </div>
  );
}
